name: doc_helper_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.7.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  injectable: ^2.5.1
  flutter_screenutil: ^5.9.3
  go_router: ^16.1.0
  firebase_auth: ^6.0.0
  json_annotation: ^4.9.0
  firebase_core: ^4.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  loader_overlay: ^5.0.0
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  retrofit_generator: ^10.0.1
  injectable_generator: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
